name: Build and Test on Develop Push

on:
  push:
    branches:
      - develop

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Build and Test
      run: |
        msbuild /restore /p:Configuration=Debug /p:Platform="Any CPU" YourSolutionFile.sln
        dotnet test YourTestProjectFolder/YourTestProject.csproj --configuration Debug

    - name: Check for code conflicts
      run: |
        git fetch --prune
        git checkout origin/master
        git merge --no-commit --no-ff origin/develop
        git diff --exit-code origin/master..HEAD
        if [ $? -ne 0 ]; then
          echo "Code conflicts detected. Please resolve conflicts before merging."
          exit 1
        fi

    - name: Sync with master branch (if no conflicts)
      if: ${{ success() }}
      run: |
        git fetch --prune
        git checkout master
        git merge --ff-only origin/develop
        git push origin master
